// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSnKEAD_PUZO5HTbDFRG683b-5ve41IoI',
    appId: '1:64058760025:web:6be3632e14a99f5eda4a48',
    messagingSenderId: '64058760025',
    projectId: 'cefmorsi-d8ffc',
    authDomain: 'cefmorsi-d8ffc.firebaseapp.com',
    storageBucket: 'cefmorsi-d8ffc.appspot.com',
    measurementId: 'G-GSCC4ZDNX3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMPwXnsn5IhqUBO1oCVRaA5CocZnbqEFQ',
    appId: '1:64058760025:android:28828d36a41ba4a3da4a48',
    messagingSenderId: '64058760025',
    projectId: 'cefmorsi-d8ffc',
    storageBucket: 'cefmorsi-d8ffc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChgiCR5Ec9vxumrYpYgx-XbSqde3ZEKLs',
    appId: '1:64058760025:ios:886fe7e39d3f59dbda4a48',
    messagingSenderId: '64058760025',
    projectId: 'cefmorsi-d8ffc',
    storageBucket: 'cefmorsi-d8ffc.appspot.com',
    androidClientId: '64058760025-10bga3lu40pqdlrsfae41seak1lk6clb.apps.googleusercontent.com',
    iosClientId: '64058760025-ijkl853t9j78lqask4opfqtsajp7qfh2.apps.googleusercontent.com',
    iosBundleId: 'com.cefmorsi.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChgiCR5Ec9vxumrYpYgx-XbSqde3ZEKLs',
    appId: '1:64058760025:ios:4b2371089706cac1da4a48',
    messagingSenderId: '64058760025',
    projectId: 'cefmorsi-d8ffc',
    storageBucket: 'cefmorsi-d8ffc.appspot.com',
    androidClientId: '64058760025-10bga3lu40pqdlrsfae41seak1lk6clb.apps.googleusercontent.com',
    iosClientId: '64058760025-e69ibkm5bsoeh3hvtvgihcvuq38j8d62.apps.googleusercontent.com',
    iosBundleId: 'com.example.cefmorsiAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDSnKEAD_PUZO5HTbDFRG683b-5ve41IoI',
    appId: '1:64058760025:web:71996e0482b6b2e3da4a48',
    messagingSenderId: '64058760025',
    projectId: 'cefmorsi-d8ffc',
    authDomain: 'cefmorsi-d8ffc.firebaseapp.com',
    storageBucket: 'cefmorsi-d8ffc.appspot.com',
    measurementId: 'G-D1YBV6E6PP',
  );
}
